### ISSUE TITLE
ClientService.createSerializedContractsListingRequest() doesn't work in 2.4.0

### ISSUE THREAD

**Issue by supl** [scalar-labs/scalardl-javascript-sdk-base#29]
It throws out this error

```
undefined this.__createContractsListingRequest is not a function
```
